language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly

before_script:
  - redis-server tests/fixtures/redis.conf

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    - RUSTDOC_VERSION=nightly
    - secure: DXGxGvhhXSVALMTwdDTc+gKtVqB1kNTe1H/1bUf2UJG3XqwrPZxMIvY2lYCOaqxaigZTuK1TPaQa3QFbE8TC8Tij3N+A2JA6PTDTy/i8RXlcGMBvoX9BptutNHF1iX0J/RWY5mlzZbcMOSajBYIeuJsaKw12NKclsmnkEoURRnNaFimrgnnX53c1neIpyd7ibag6egBsJ/LU/CDe2MfiO7xbINl8iyudwdGrQF1HeP97vgfmdvF3QTx8/Hx9p6uMgpHeQ0MMTLvwu31UPvRllHE9tEmUdU6rNdYrQU4VM7TaqhUiw/JBynvW4UEGDzp4uemX7/0bHzj9IYnjoLh5P/b6ROYFHRkWGO+TrWYCO77Vp3kT4DCAIQMSJ8kpdL17i40iBpyYiicoeW49K5gy1qjRSpblmVRr2tBddt79daj9J4fRtE2ZFWuz2hwaJ30qm2Z1re48f5EilbIwEyVaN2y30nseaY+jlQjJubscMz7HjAIyP10VTgAFl5cz9sCD/6vVORzgf9WpGuqKy3KQ9tPsnyxnQfP0bhhRRe2ypbVcaexHeJ/Alwkyiz0nzsiw08P5bHDLYH5SmOsCNOfvyp4kcF+GuvsVFTdKHBokP24HMlmdnHyfcQ+MQFXfN999jGB7D+oTQy4LBxCveEaVUPtQ8IYlZdgWio6akloTJFI=

notifications:
  email: false
