language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

before_script:
  - redis-server tests/fixtures/redis.conf

after_success:
  - curl https://stainless-steel.github.io/travis/documentation.sh | bash

env:
  global:
    - secure: hyDgK7PiTQQQBAHGU0P7caPF1Cuix1cNOdzfGPcw2UHa7c4UjwR9tVhueQ5QTxH0m9qEcBuPSne9+rGLetmOZ1Bp9/t0UZRTTuol7K5IilQi5d4qZvpphR0lJPXDb8/DTCk+TJSvttnhoZ3J9pQRlQYLp65+d9QcRKz254yjHiSJ2LXe+Dl9j/ys9GwN3PHXMl1lXa7jljZKCbNyLOFDogkMDR7gW9lUjK1t0S7ET/nLS7ABxiZBO4eV92miHh5UEdTk8prcdgvTyHFEk+NcleqKMuBrxCiZ99GjqG/8m0b7XhTQB943wsV8a1GZno8+tpbRBadkFIJhdA2GXKmpdvmVS8GOQrKNK7BNVsUydh5hFsHDY3QXbkfhyIBUItCas+/G4omzNYhvTpxr/elmkkEx5HxIZ5WFaPNBOBgP9ycrrQgu4Nhyu49+O1Xen77sguHM3Ekip1un0jZMiTDGLj2X8ewJCOW172DbgAyAP3qTVkRkwtKetsK624RIhWY1DCqcNY4NjOcjs3RNVipC73NgAfBsrpg+u5qZ0zsNVNwCVYTUM589fRrFBOaIemS/VK0WdsBa0fLTA2BeawIrbgxBZYqgEaNTIlzQrVlSKdG5hj/vADcdT0aptEEeubpWTLpEoEeQfFwNCwAYkalbAGnWki9bD3lwgvd2UV73bDY=

notifications:
  email: false
